trailingComma: 'es5'
endOfLine: 'lf'
printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
overrides:
  - files: '*.sol'
    options:
      tabWidth: 4
      singleQuote: false
      bracketSpacing: false
